name: Build Snapcast Client

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Buildroot dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget cpio rsync file bc flex bison libssl-dev libncurses5-dev python3 sudo quilt unzip libgnutls28-dev bmap-tools

      - name: Write RAUC secrets to files
        run: |
          mkdir -p buildroot-external/openssl-ca/dev/private
          printf '%s' "${{ secrets.RAUC_KEY }}" > buildroot-external/openssl-ca/dev/private/development-1.key.pem
          printf '%s' "${{ secrets.RAUC_CERT }}" > buildroot-external/openssl-ca/dev/development-1.cert.pem
          printf '%s' "${{ secrets.RAUC_CA }}" > buildroot-external/openssl-ca/dev/ca.cert.pem

      - name: Build default target
        run: |
          make raspberrypi4-64-rauc

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/images
