name: Nightly Buildroot Update PR

on:
  schedule:
    # Run every night at 02:15 UTC
    - cron: "15 2 * * *"
  workflow_dispatch:

jobs:
  update-buildroot:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # allow pushing a branch
      pull-requests: write # allow creating the PR

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # we need full history to push a new branch

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure buildroot submodule is on 2025.05.x branch & fetch latest
        id: update
        shell: bash
        run: |
          set -euo pipefail
          # Move into the submodule directory, make sure correct branch is tracked
          pushd buildroot
          git fetch origin 2025.05.x --depth=1
          NEW_SHA=$(git rev-parse origin/2025.05)
          CUR_SHA=$(git rev-parse HEAD)
          echo "Current SHA: $CUR_SHA"
          echo "Latest  SHA: $NEW_SHA"
          if [ "$NEW_SHA" = "$CUR_SHA" ]; then
            echo "::set-output name=changed::false"
          else
            git checkout $NEW_SHA
            echo "::set-output name=changed::true"
          fi
          popd

          # Stage submodule pointer if it changed
          if [[ "$(git diff --quiet buildroot || echo 'dirty')" == 'dirty' ]]; then
            git add buildroot
          fi

      - name: Commit submodule update
        if: steps.update.outputs.changed == 'true'
        run: |
          git commit -m "chore: update buildroot submodule to latest 2025.05.x"

      - name: Create Pull Request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: Update buildroot submodule (2025.05.x)"
          body: |
            Automated nightly PR to update the buildroot submodule to the latest commit on the 2025.05.x branch.
          commit-message: "chore: update buildroot submodule to latest 2025.05.x"
          branch: buildroot-update-2025.05.x
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
