name: Nightly Buildroot Update PR

on:
  schedule:
    # Run every night at 02:15 UTC
    - cron: "15 2 * * *"
  workflow_dispatch:

jobs:
  update-buildroot:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # allow pushing a branch
      pull-requests: write # allow creating the PR

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # we need full history to push a new branch

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure buildroot submodule tracks latest release tag
        id: update
        shell: bash
        run: |
          set -euo pipefail
          # Move into the submodule directory, discover latest release tag
          pushd buildroot
          # Fetch tags from origin and determine the newest release tag (e.g., 2025.08.1)
          git fetch --tags --force --depth=1 origin "refs/tags/*:refs/tags/*"
          LATEST_TAG=$(git tag -l --sort=-version:refname | grep -E '^[0-9]{4}\.[0-9]{2}(\.[0-9]+)?$' | head -n1)
          if [ -z "${LATEST_TAG:-}" ]; then
            echo "Failed to detect latest Buildroot release tag" >&2
            exit 1
          fi
          NEW_SHA=$(git rev-list -n1 "$LATEST_TAG")
          CUR_SHA=$(git rev-parse HEAD)
          echo "Current SHA: $CUR_SHA"
          echo "Latest  Tag: $LATEST_TAG -> $NEW_SHA"
          if [ "$NEW_SHA" = "$CUR_SHA" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git checkout "$NEW_SHA"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
          echo "latest_tag=${LATEST_TAG}" >> "$GITHUB_OUTPUT"
          popd

          # Stage submodule pointer if it changed
          if [[ "$(git diff --quiet buildroot || echo 'dirty')" == 'dirty' ]]; then
            git add buildroot
          fi

      - name: Commit submodule update
        if: steps.update.outputs.changed == 'true'
        run: |
          git commit -m "chore: update buildroot submodule to ${LATEST_TAG}"

      - name: Create Pull Request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: Update buildroot submodule to ${{ steps.update.outputs.latest_tag }}"
          body: |
            Automated nightly PR to update the buildroot submodule to the latest Buildroot release tag: ${{ steps.update.outputs.latest_tag }}.
          commit-message: "chore: update buildroot submodule to ${{ steps.update.outputs.latest_tag }}"
          branch: buildroot-update-${{ steps.update.outputs.latest_tag }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
