name: Check for Snapcast Updates

on:
  schedule:
    # Run every day at 03:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write  # Needed for OIDC token

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get latest Snapcast version
        id: version
        run: |
          # Get the latest release version from GitHub API
          LATEST_VERSION=$(curl -s https://api.github.com/repos/badaix/snapcast/releases/latest | jq -r '.tag_name')
          echo "Latest Snapcast version: $LATEST_VERSION"
          
          # Get current version from the makefile
          CURRENT_VERSION=$(grep 'SNAPCAST_VERSION = ' buildroot-external/package/snapcast/snapcast.mk | cut -d'=' -f2 | xargs)
          echo "Current Snapcast version: $CURRENT_VERSION"
          
          # Compare versions
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "New version available: $LATEST_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            
            # Create a branch name with the new version
            BRANCH_NAME="update/snapcast-${LATEST_VERSION#v}"
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          else
            echo "No new version available"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update version and create PR
        if: steps.version.outputs.version_changed == 'true'
        run: |
          # Check if branch already exists
          if git show-ref --verify --quiet refs/remotes/origin/${{ steps.version.outputs.branch_name }}; then
            echo "Branch ${{ steps.version.outputs.branch_name }} already exists, skipping PR creation"
            exit 0
          fi
          
          # Create a new branch
          git checkout -b ${{ steps.version.outputs.branch_name }}
          
          # Update the version in the makefile
          sed -i "s/SNAPCAST_VERSION = .*/SNAPCAST_VERSION = ${{ steps.version.outputs.new_version }}/" buildroot-external/package/snapcast/snapcast.mk
          
          # Commit the changes
          git add buildroot-external/package/snapcast/snapcast.mk
          git commit -m "Update Snapcast to ${{ steps.version.outputs.new_version }}"
          
          # Push the branch
          git push -u origin ${{ steps.version.outputs.branch_name }}
          
          # Get the current version from the file for the PR body
          CURRENT_VERSION=$(grep 'SNAPCAST_VERSION = ' buildroot-external/package/snapcast/snapcast.mk | cut -d'=' -f2 | xargs)
          
          # Create PR using the GitHub API directly with the token
          PR_BODY=$(cat << EOF
          {
            "title": "Update Snapcast to ${{ steps.version.outputs.new_version }}",
            "body": "This PR updates Snapcast from $CURRENT_VERSION to ${{ steps.version.outputs.new_version }}",
            "head": "${{ steps.version.outputs.branch_name }}",
            "base": "main"
          }
          EOF
          )
          
          PR_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$PR_BODY" \
            "https://api.github.com/repos/${{ github.repository }}/pulls")
          
          # Check if PR was created successfully
          if echo "$PR_RESPONSE" | grep -q '"number"'; then
            echo "PR created successfully"
          else
            echo "Error creating PR: $PR_RESPONSE"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
